In [1]:
import pandas as pd

pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.7.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19045
machine               : AMD64
processor             : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : Korean_Korea.949

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 75.1.0
pip                   : 24.2
Cython                : None
pytest                : 7.4.4
hypothesis            : None
sphinx                : 7.3.7
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 5.2.1
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.4
IPython               : 8.27.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : 1.3.7
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.6.1
gcsfs                 : None
matplotlib            : 3.9.2
numba                 : 0.60.0
numexpr               : 2.8.7
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : None
pyarrow               : 16.1.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : 2024.6.1
scipy                 : 1.13.1
sqlalchemy            : 2.0.34
tables                : 3.10.1
tabulate              : 0.9.0
xarray                : 2023.6.0
xlrd                  : None
zstandard             : 0.23.0
tzdata                : 2023.3
qtpy                  : 2.4.1
pyqt5                 : None

In [2]:
nsmc_train_df = pd.read_csv('ratings_train.txt', encoding = 'utf8', sep = '\t', engine = 'python')

nsmc_train_df.head()

         id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [3]:
nsmc_train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        150000 non-null  int64
 1   document  149995 non-null  object
 2   label     150000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 3.4+ MB

In [4]:
nsmc_train_df = nsmc_train_df[nsmc_train_df['document'].notnull()]
nsmc_train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 149995 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        149995 non-null  int64
 1   document  149995 non-null  object
 2   label     149995 non-null  int64
dtypes: int64(2), object(1)
memory usage: 4.6+ MB

In [5]:
nsmc_train_df['label'].value_counts()

0    75170
1    74825
Name: label, dtype: int64

In [6]:
import re

nsmc_train_df['document'] = nsmc_train_df['document'].apply(lambda x : re.sub(r'[^ ㄱ-ㅣ가-힣]+', " ", x))
nsmc_train_df.head()

         id                                           document  label
0   9976970                                 아 더빙  진짜 짜증나네요 목소리      0
1   3819312                       흠 포스터보고 초딩영화줄 오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                        교도소 이야기구먼  솔직히 재미는 없다 평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화 스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [7]:
nsmc_test_df = pd.read_csv('ratings_test.txt', encoding = 'utf8', sep = '\t', engine = 'python')
nsmc_test_df.head()

        id                                           document  label
0  6270596                                                굳 ㅋ      1
1  9274899                               GDNTOPCLASSINTHECLUB      0
2  8544678             뭐야 이 평점들은.... 나쁘진 않지만 10점 짜리는 더더욱 아니잖아      0
3  6825595                   지루하지는 않은데 완전 막장임... 돈주고 보기에는....      0
4  6723715  3D만 아니었어도 별 다섯 개 줬을텐데.. 왜 3D로 나와서 제 심기를 불편하게 하죠??      0

In [8]:
nsmc_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        50000 non-null  int64
 1   document  49997 non-null  object
 2   label     50000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.1+ MB

In [9]:
nsmc_test_df = nsmc_test_df[nsmc_test_df['document'].notnull()]

In [10]:
nsmc_test_df['label'].value_counts()

1    25171
0    24826
Name: label, dtype: int64

In [11]:
nsmc_test_df['document'] = nsmc_test_df['document'].apply(lambda x : re.sub(r'[^ ㄱ-ㅣ가-힣]+', " ", x))
nsmc_test_df.head()

        id                                       document  label
0  6270596                                            굳 ㅋ      1
1  9274899                                                     0
2  8544678             뭐야 이 평점들은  나쁘진 않지만  점 짜리는 더더욱 아니잖아      0
3  6825595                    지루하지는 않은데 완전 막장임  돈주고 보기에는       0
4  6723715   만 아니었어도 별 다섯 개 줬을텐데  왜  로 나와서 제 심기를 불편하게 하죠       0

In [12]:
!pip install konlpy

Requirement already satisfied: konlpy in c:\anaconda3\lib\site-packages (0.6.0)
Requirement already satisfied: lxml>=4.1.0 in c:\anaconda3\lib\site-packages (from konlpy) (4.6.3)
Requirement already satisfied: numpy>=1.6 in c:\anaconda3\lib\site-packages (from konlpy) (1.20.1)
Requirement already satisfied: JPype1>=0.7.0 in c:\anaconda3\lib\site-packages (from konlpy) (1.3.0)

In [13]:
from konlpy.tag import Okt

okt = Okt()

In [14]:
def okt_tokenizer(text):
    tokens = okt.morphs(text)
    return tokens

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(tokenizer = okt_tokenizer, ngram_range = (1, 2), min_df = 3, max_df = 0.9)
tfidf.fit(nsmc_train_df['document'])
nsmc_train_tfidf = tfidf.transform(nsmc_train_df['document'])

C:\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:489: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn("The parameter 'token_pattern' will not be used"

In [16]:
print(type(nsmc_train_tfidf))

<class 'scipy.sparse.csr.csr_matrix'>

In [17]:
from sklearn.linear_model import LogisticRegression

SA_lr = LogisticRegression(random_state = 0)

In [18]:
SA_lr.fit(nsmc_train_tfidf, nsmc_train_df['label'])

C:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(random_state=0)

In [19]:
from sklearn.model_selection import GridSearchCV

params = {'C': [1, 3, 3.5, 4, 4.5, 5]}
SA_lr_grid_cv = GridSearchCV(SA_lr, param_grid = params, cv = 3, scoring = 'accuracy', verbose = 1)

In [20]:
SA_lr_grid_cv.fit(nsmc_train_tfidf, nsmc_train_df['label'])

Fitting 3 folds for each of 6 candidates, totalling 18 fits

C:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

GridSearchCV(cv=3, estimator=LogisticRegression(random_state=0),
             param_grid={'C': [1, 3, 3.5, 4, 4.5, 5]}, scoring='accuracy',
             verbose=1)

In [21]:
print(SA_lr_grid_cv.best_params_, round(SA_lr_grid_cv.best_score_, 4))

{'C': 3} 0.8553

In [22]:
SA_lr_best = SA_lr_grid_cv.best_estimator_

In [23]:
nsmc_test_tfidf = tfidf.transform(nsmc_test_df['document'])

In [24]:
test_predict = SA_lr_best.predict(nsmc_test_tfidf)

In [25]:
print(len(test_predict))

49997

In [26]:
from sklearn.metrics import accuracy_score

print('감성 분석 정확도 : ', round(accuracy_score(nsmc_test_df['label'], test_predict), 3))

감성 분석 정확도 :  0.858

In [27]:
#네이버 에르메스 분석

In [29]:
import json

file_name = '에르메스_naver_news'
with open(file_name + '.json', encoding = 'utf8') as j_f:
    data = json.load(j_f)

In [30]:
print(data)

[{'cnt': 1, 'description': '<b>에르메스</b>와 롤렉스는 매년 한 차례 씩 가격을 인상해왔다. 일각에서는 리오프닝(경제활동 재개)으로 꺾인 명품 소비심리에 가격 인상을 자제할 것이라는 시각도 있다. 산업통상자원부에 따르면 올해 4월 백화점... ', 'link': 'https://n.news.naver.com/mnews/article/011/0004063808?sid=101', 'org_link': 'https://www.sedaily.com/NewsView/2677CAEZE0', 'pDate': '2022-06-11 08:01:00', 'title': '&quot;결혼식 교복이냐&quot; 굴욕 겪은 샤넬…또 가격 인상설 솔솔'}, {'cnt': 2, 'description': '이전에도 삼성과 톰브라운, 애플과 <b>에르메스</b>의 스마트워치 협업 소식은 있었습니다. 인기있는 브랜드 혹은 디자인 능력을 가진 명품 브랜드, 혹은 팬덤을 가진 남성 그룹 방탄소년단 등과의 협업 등 테크업계서도... ', 'link': 'https://n.news.naver.com/mnews/article/081/0003279307?sid=105', 'org_link': 'https://www.seoul.co.kr/news/newsView.php?id=20220610500148&wlog_tag3=naver', 'pDate': '2022-06-10 20:57:00', 'title': '너도 나도 팔목에 스마트워치…결국 ‘이 브랜드’ 관심 끌었다 [명품톡+]'}, {'cnt': 3, 'description': "루이비통 제공 \xa0<b>에르메스</b>, 구찌, 디올 등 콧대 높은 명품 브랜드들이 국내에서 레스토랑을 열고 체험형... 참고로 국내에서 가장 먼저 체험형 마케팅 나선 곳은 '<b>에르메스</b>'다. 2006년 도산파크 지하에 '카페 마당'을... ", 'link': 'http://www.sporbiz.co.kr/news/articleView.html?idxno=621747', 'org_link': 'http://www.sporbiz.co.kr/news/articleView.html?idxno=621747', 'pDate': '2022-06-10 14:50:00', 'title': "구찌·디올에 이어 세계 최초 루이비통 레스토랑까지... 왜 '코리아'일까"}, {'cnt': 4, 'description': '또, <b>에르메스</b>, 구찌, 랑콤, 디올, 다이슨 등 명품 브랜드 방송의 메인 셀러로 활약하며 프리미엄 라이프스타일 리더로서의 이미지를 구축하고 있다. 라이버스는 쇼호스트 오하나를 시작으로 ▲홍다움찬 ▲김도현... ', 'link': 'http://www.lawissue.co.kr/view.php?ud=202206100936042689204ead0791_12', 'org_link': 'http://www.lawissue.co.kr/view.php?ud=202206100936042689204ead0791_12', 'pDate': '2022-06-10 09:38:00', 'title': '[유통 이슈] 헨켈홈케어코리아 브레프-패스트파이브, ‘상쾌한 화장실 조성 캠...'}, {'cnt': 5, 'description': "“가격에 입틀막” 오은영, <b>에르메스</b> VVIP 논란 이어 '초고가 명품 시계' 착용 오은영, 초고가 롤렉스 시계 착용 '눈길'…가격만 5000만 원대 위키트리 | 세상을 깨우는 재미진 목소리 또 지난해 어느 누리꾼이 &quot;오... ", 'link': 'https://www.wikitree.co.kr/articles/762060', 'org_link': 'https://www.wikitree.co.kr/articles/762060', 'pDate': '2022-06-10 08:42:00', 'title': "'10분 진료비가 9만원' 오은영 박사가 타고 다니는 차, 차원이 다른 수준이다"}, {'cnt': 6, 'description': '해외에선 이미 <b>에르메스</b>와 파타고니아, 나이키 등이 업사이클링 제품 개발에 뛰어들었다. 코오롱인더스트리FnC부문(이하 코오롱FnC)은 최근 소셜벤처 케이오에이(K.O.A)를 인수했다. 지속가능성을 추구하는 케이오에이와... ', 'link': 'https://n.news.naver.com/mnews/article/648/0000008440?sid=101', 'org_link': 'http://news.bizwatch.co.kr/article/consumer/2022/06/09/0006', 'pDate': '2022-06-10 06:51:00', 'title': "패션업계가 '느림의 미학'에 빠진 이유"}, {'cnt': 7, 'description': '브랜드인 <b>에르메스</b>의 ‘버킨백’이다. 미국 로스앤젤레스에서 의류 매장을 운영하는 메이슨... <b>에르메스</b>는 2022년 1월 뉴욕 남부 연방지방법원에 로스차일드를 상대로 등록 상표권 침해, <b>에르메스</b>가 상표 사용을... ', 'link': 'https://n.news.naver.com/mnews/article/050/0000061005?sid=101', 'org_link': 'https://magazine.hankyung.com/business/article/202206016595b', 'pDate': '2022-06-10 06:02:00', 'title': '모피로 덮인 <b>에르메스</b> 버킨백 NFT, 합법일까 위법일까[김윤희의 지식재산권 산...'}, {'cnt': 8, 'description': '리바이스 매출 100억 달러 계획은 트렁크로 시작한 루이비통이나 말 안장의 <b>에르메스</b> 등 가죽 제품으로 출발한 유럽 명품 브랜드들이 지속 가능 패션 추세에 쫓겨 새로운 대체 소재 개발에 몰두하고 있는 것과... ', 'link': 'http://www.apparelnews.co.kr/news/news_view/?idx=198365', 'org_link': 'http://www.apparelnews.co.kr/news/news_view/?idx=198365', 'pDate': '2022-06-10 00:06:00', 'title': '리바이스 “2027년까지 연 6~7% 성장…100억 달러 달성”'}, {'cnt': 9, 'description': '국내에선 <b>에르메스</b>가 가장 먼저 식음료 매장을 선보였다. 2006년 도산파크 지하에 ‘카페 마당’을 열었다. 600만원 레이디백 대신 2만원 디올 라떼 그간 ‘콧대 높은 마케팅’으로 폐쇄적인 느낌이 강했던 명품 매장들은... ', 'link': 'https://n.news.naver.com/mnews/article/015/0004709577?sid=101', 'org_link': 'https://www.hankyung.com/economy/article/2022060902001', 'pDate': '2022-06-09 17:03:00', 'title': "600만원 디올백 대신 2만원 라떼…요즘 뜨는 '인증샷' 성지"}, {'cnt': 10, 'description': '환구시보에 따르면 <b>에르메스</b>, 루이비통, 크리스찬 디올 등 입주 매장들은 개장 첫날 각각 100만위안(14만9000달러)이 넘는 매출을 올렸다. 상하이 뿐 아니라 베이징에서도 명품 소비가 늘고 있는 것으로 전해졌다. 베이징... ', 'link': 'https://n.news.naver.com/mnews/article/009/0004975350?sid=104', 'org_link': 'http://news.mk.co.kr/newsRead.php?no=505439&year=2022', 'pDate': '2022-06-09 11:53:00', 'title': "<b>에르메스</b>, 루이뷔통…'명품에 환장한 중국', 봉쇄 이후 보복소비"}, {'cnt': 11, 'description': '불리는 <b>에르메스</b>의 지위를 구축하려는 것으로 보고 있다. 샤넬은 지난해 10월부터 특정 제품에 대해 1년에 1개씩만 살 수 있는 구매제한 정책을 시행했는데, 이는 <b>에르메스</b>가 오래전에 도입한 전략이다. 필리프... ', 'link': 'https://n.news.naver.com/mnews/article/009/0004975328?sid=103', 'org_link': 'http://news.mk.co.kr/newsRead.php?no=505303&year=2022', 'pDate': '2022-06-09 11:25:00', 'title': '샤넬 주얼리도 올랐다…평균 10% 가격 인상'}, {'cnt': 12, 'description': '스웨이드 부츠 가격 미정, <b>에르메스</b>. 나일론 블루종 가격 미정, <b>에르메스</b>. 더블 브레스티드 수트, 실크 셔츠 가격 미정, 모두 톰포드. 왼쪽부터ㅣ페이턴트 레더 재킷 3백80만원대, 베르사체 at yoox.com. 더블 브리지... ', 'link': 'https://www.gqkorea.co.kr/2022/06/09/%ec%84%b8-%eb%82%a8%ec%9e%90%ec%9d%98-%ec%9d%bc%ed%83%88-%eb%93%9c%eb%9d%bc%ec%9d%b4%eb%b8%8c/?utm_source=naver&utm_medium=partnership', 'org_link': 'https://www.gqkorea.co.kr/2022/06/09/%ec%84%b8-%eb%82%a8%ec%9e%90%ec%9d%98-%ec%9d%bc%ed%83%88-%eb%93%9c%eb%9d%bc%ec%9d%b4%eb%b8%8c/?utm_source=naver&utm_medium=partnership', 'pDate': '2022-06-09 10:04:00', 'title': '세 남자의 일탈 드라이브'}, {'cnt': 13, 'description': '웨스트는 존스의 관심을 끌기 위해 고가의 <b>에르메스</b> 버킨백을 선물해 주목을 받았다. 연예매체 페이지식스는 3월 31일(현지시간) “카녜이 웨스트가 27만 5,000달러(약 3억 3400만원)에 달하는 매우 희귀한 버전의 가방을... ', 'link': 'https://n.news.naver.com/mnews/article/117/0003612003?sid=106', 'org_link': 'http://www.mydaily.co.kr/new_yk/html/read.php?newsid=202206090954297474&ext=na&utm_campaign=naver_news&utm_source=naver&utm_medium=related_news', 'pDate': '2022-06-09 09:56:00', 'title': '‘킴 카다시인과 도플갱어’ 24살 모델, “내가 카녜이 웨스트와 결별? 가짜뉴...'}, {'cnt': 14, 'description': "연극 '그을린 사랑', 양손프로젝트의 '배신', 국립창극단 '트로이의 여인들', 뮤지컬 '지저스 크라이스트 수퍼스타' '도리안 그레이의 초상', 무용극 '어린왕자' '사군자, 생의 계절' 그리고 <b>에르메스</b> 재단 미술상을... ", 'link': 'https://n.news.naver.com/mnews/article/003/0011236947?sid=106', 'org_link': 'http://www.newsis.com/view/?id=NISX20220609_0001901062&cID=10601&pID=10600', 'pDate': '2022-06-09 09:51:00', 'title': "정재일, 세계적 음악레이블 '데카'와 글로벌 계약"}, {'cnt': 15, 'description': '길어진 ‘집콕’으로 인해 옷에 대한 수요가 줄면서 소비자들이 이왕 살 거면 <b>에르메스</b> 등 하이엔드급 명품을 사거나 남들은 안 입는 희소성이 있는 스트리트 패션 브랜드에 지갑을 열고 있다는 분석이다. 이 같은... ', 'link': 'https://n.news.naver.com/mnews/article/015/0004709292?sid=101', 'org_link': 'https://www.hankyung.com/economy/article/202206070759i', 'pDate': '2022-06-09 09:12:00', 'title': "30년 1위 자리 폴로에 내줬다…'토종 패션' 빈폴의 위기[박동휘의 컨슈머 리포..."}, {'cnt': 16, 'description': "불리는 '에·루·샤(<b>에르메스</b>·루이비통·샤넬)' 브랜드도 없이 불리함을 극복한 더현대서울의 비밀은 과연... 백화점 성공 공식으로 통하는 해외 3대 명품 브랜드 '에루샤(<b>에르메스</b>·루이비통·샤넬)' 매장 유치도 되지... ", 'link': 'http://www.ntoday.co.kr/news/articleView.html?idxno=92042', 'org_link': 'http://www.ntoday.co.kr/news/articleView.html?idxno=92042', 'pDate': '2022-06-08 19:30:00', 'title': "[뉴리테일 &amp; 더현대 ①] 유통 불모지 입성한 더현대서울, '취향 쪼개기'로 진..."}, {'cnt': 17, 'description': '모두 <b>에르메스</b> 여유 있는 실루엣과 채도 높은 컬러나 프린트에 몸을 타고 흐르는 소재로 경쾌한 에너지를... 모두 <b>에르메스</b> 감각을 불어넣는 특급 처방전! 목에 두르던 스카프를 벨트로 연출해보자. 편안한 디자인과... ', 'link': 'https://magazine.hankyung.com/money/article/202205223052c', 'org_link': 'https://magazine.hankyung.com/money/article/202205223052c', 'pDate': '2022-06-08 17:38:00', 'title': '[Men’s Look] 셔츠 입기 좋은 지금'}, {'cnt': 18, 'description': '4월 말 마감의 <b>에르메스</b> 1분기 매출은 지난해보다 15% 늘어난 27억 유로, 미국 시장 증가율은 44%에 달했다. 루이비통의 LVMH나 구찌의 케어링 그룹, 까르띠에의 리치몬트 그룹도 비슷한 추세다. 미국 명품 브랜드인 랄프... ', 'link': 'https://n.news.naver.com/mnews/article/469/0000679514?sid=105', 'org_link': 'https://hankookilbo.com/News/Read/A2022060816520004852?did=NA', 'pDate': '2022-06-08 17:15:00', 'title': '쌓여가는 대중 브랜드 재고…美\xa0패션시장, 명품만 잘 팔린다'}, {'cnt': 19, 'description': "<b>에르메스</b>를 떠올리면 오렌지, 티파니는 블루, 맥도날드는 노란 대문자 'M'을 연상하게 된다. 색깔, 이니셜 외 '숫자'를 활용하는 경우도 많다. 그간 무심코 지나쳤던 상호명 뒤 그림자처럼 붙어있는 숫자는 단순한... ", 'link': 'http://www.m-i.kr/news/articleView.html?idxno=925096', 'org_link': 'http://www.m-i.kr/news/articleView.html?idxno=925096', 'pDate': '2022-06-08 15:18:00', 'title': '[기획] 교촌 1991‧ GS25에 담긴 비밀은?'}, {'cnt': 20, 'description': '심플해 보이는 메이크업 방법으로 유명한 이 대가는 최근 <b>에르메스</b> 뷰티의 크리에이티브 디렉터로... &lt;보그 영국&gt;이 <b>에르메스</b>라는 상징적인 패션 하우스의 뷰티 브랜드에 대한 그의 비전, 작업하는 제품에 느끼는... ', 'link': 'https://www.vogue.co.kr/2022/06/07/%ec%97%90%eb%a5%b4%eb%a9%94%ec%8a%a4-%eb%b7%b0%ed%8b%b0%ec%9d%98-%ec%83%88%eb%a1%9c%ec%9a%b4-%eb%b9%84%ec%a0%84/?utm_source=naver&utm_medium=partnership', 'org_link': 'https://www.vogue.co.kr/2022/06/07/%ec%97%90%eb%a5%b4%eb%a9%94%ec%8a%a4-%eb%b7%b0%ed%8b%b0%ec%9d%98-%ec%83%88%eb%a1%9c%ec%9a%b4-%eb%b9%84%ec%a0%84/?utm_source=naver&utm_medium=partnership', 'pDate': '2022-06-08 10:42:00', 'title': '<b>에르메스</b> 뷰티의 새로운 비전'}, {'cnt': 21, 'description': '웨스트는 존스의 관심을 끌기 위해 고가의 <b>에르메스</b> 버킨백을 선물해 주목을 받았다. 연예매체 페이지식스는 3월 31일(현지시간) “카녜이 웨스트가 27만 5,000달러(약 3억 3400만원)에 달하는 매우 희귀한 버전의 가방을... ', 'link': 'https://n.news.naver.com/mnews/article/117/0003611559?sid=106', 'org_link': 'http://www.mydaily.co.kr/new_yk/html/read.php?newsid=202206081005571900&ext=na&utm_campaign=naver_news&utm_source=naver&utm_medium=related_news', 'pDate': '2022-06-08 10:06:00', 'title': '44살 카녜이 웨스트, ‘킴 카다시안 도플갱어’ 24살 여친과 5개월만에 결별[...'}, {'cnt': 22, 'description': '판매자 측면 뿐 아니라 구매자 측면에서도 S+급, A급 등 새상품 혹은 새상품과 동일한 컨디션의 ‘<b>에르메스</b>’, ‘샤넬’, ‘루이비통’ 등 인기 브랜드 상품을 새상품 가격보다 20~50% 저렴한 가격에 구입할 수 있어 구매... ', 'link': 'https://www.viva100.com/main/view.php?key=20220608010001490', 'org_link': 'https://www.viva100.com/main/view.php?key=20220608010001490', 'pDate': '2022-06-08 10:04:00', 'title': '트렌비, 명품 리셀 서비스 약 14만40000건, 총 거래액 약 1690억원 돌파'}, {'cnt': 23, 'description': '배우 박연수가 명품 가방을 직접 리폼했다. 8일 박연수는 자신의 인스타그램에 &quot;안녕~ 잘가~ 오래된 나의 에르백~&quot;이라며 명품 가방을 직접 수선한 모습을 게재했다. 박연수는 &quot;가방이 하나만 있는것도 아닌데 유독 이가방만... ', 'link': 'https://n.news.naver.com/mnews/article/076/0003878168?sid=106', 'org_link': 'http://sports.chosun.com/news/ntype.htm?id=202206090100050900003159&servicedate=20220608', 'pDate': '2022-06-08 09:27:00', 'title': "'싱글맘' 박연수, <b>에르메스</b> 가방에 칼 댔다…&quot;세상 하나밖에 없어&quot;"}, {'cnt': 24, 'description': '공개된 사진에는 박연수가 가죽공방을 찾아 <b>에르메스</b> 가방을 리폼하고 있는 모습이 담겨있다. 오래된 명품 가방이 새 가방으로 재탄생해 눈길을 끈다. 박연수는 &quot;천부분은 수강생 추천 가죽으로 교체하여 구멍 뚫고... ', 'link': 'https://n.news.naver.com/mnews/article/112/0003564146?sid=106', 'org_link': 'http://biz.heraldcorp.com/view.php?ud=202206080906516787727_1', 'pDate': '2022-06-08 09:16:00', 'title': '박연수, <b>에르메스</b>백 직접 리폼..&quot;세상에서 하나밖에 없어 소중&quot;'}, {'cnt': 25, 'description': '조현범은 장모인 김윤옥에게 1200만 원에 이르는 <b>에르메스</b> 핸드백을 선물해 구설수에 오르기도 했다. 조현범은 당시 김씨의 블로그에 사과문 형식의 글을 올려 &quot;제품 가격이 일반인 정서에 안 맞는다는 생각은 미처... ', 'link': 'https://www.businesspost.co.kr/BP?command=article_view&num=283216', 'org_link': 'https://www.businesspost.co.kr/BP?command=article_view&num=283216', 'pDate': '2022-06-08 08:34:00', 'title': '[Who Is ?] 조현범 한국앤컴퍼니 대표이사 회장'}, {'cnt': 26, 'description': "롤스로이스나 <b>에르메스</b> 같은 하이엔드 '끝판왕'도 있지만, 한국을 비롯해 전 세계 남녀노소 대부분이 명품의 대명사로 포르쉐와 함께 루이비통을 고르곤 한다. 특히 '오픈런'으로 대표되는 국내 럭셔리 붐으로 명품제국... ", 'link': 'https://n.news.naver.com/mnews/article/008/0004755541?sid=103', 'org_link': 'http://news.mt.co.kr/mtview.php?no=2022060711162449254', 'pDate': '2022-06-08 05:30:00', 'title': '루이비통 의자 1.3억·소파 9천만원…&quot;백화점엔 없다&quot; 2030 몰려간 곳'}, {'cnt': 27, 'description': '긴자는 일본에서 가장 땅값이 비싼 곳으로 ‘에루샤’(<b>에르메스</b>, 루이비통, 샤넬)를 비롯해 온갖 명품 매장이 다 있는 거리다. 그런 콧대 높은 곳에 어울리지 않는 각종 100엔숍과 300엔숍이 지난해부터 지난달까지... ', 'link': 'https://n.news.naver.com/mnews/article/081/0003278579?sid=110', 'org_link': 'https://www.seoul.co.kr/news/newsView.php?id=20220608030009&wlog_tag3=naver', 'pDate': '2022-06-08 05:09:00', 'title': '[특파원 칼럼] 긴자 거리의 100엔숍과 추락하는 소득/김진아 도쿄특파원'}, {'cnt': 28, 'description': "이번 10주년 이벤트는 1차로 프랑스 명품 브랜드 특집으로 '샤넬', '<b>에르메스</b>', '루이비통' '디올' 등을 리본즈 스토어를 통해 새 상품은 물론 빈티지 제품을 합리적인 가격에 구매할 수 있는 특가세일을 진행한다. 또한... ", 'link': 'https://n.news.naver.com/mnews/article/008/0004755486?sid=101', 'org_link': 'http://news.mt.co.kr/mtview.php?no=2022060712171190002', 'pDate': '2022-06-07 17:57:00', 'title': "리본즈, '론칭 10주년 기념' 고객 감사 이벤트 진행"}, {'cnt': 29, 'description': '이번 10주년 이벤트는 1차로 프랑스 명품 브랜드 특집으로 ‘샤넬’, ‘<b>에르메스</b>’, ‘루이비통’ ‘디올’ 등을 리본즈 스토어를 통해 새상품은 물론 빈티지 제품을 합리적인 가격에 구매할 수 있는 특가 세일을... ', 'link': 'http://www.fashionbiz.co.kr/TN/?cate=2&recom=2&idx=192824', 'org_link': 'http://www.fashionbiz.co.kr/TN/?cate=2&recom=2&idx=192824', 'pDate': '2022-06-07 14:52:00', 'title': '리본즈, ‘론칭 10주년 기념’ 고객 감사 이벤트 진행'}, {'cnt': 30, 'description': '이번 10주년 이벤트는 1차로 프랑스 명품 브랜드 특집으로 ‘샤넬’, ‘<b>에르메스</b>’, ‘루이비통’ ‘디올’ 등을 리본즈 스토어를 통해 새상품은 물론 빈티지 제품을 합리적인 가격에 구매할 수 있는 특가 세일을... ', 'link': 'http://www.lawissue.co.kr/view.php?ud=20220607111700730204ead0791_12', 'org_link': 'http://www.lawissue.co.kr/view.php?ud=20220607111700730204ead0791_12', 'pDate': '2022-06-07 11:18:00', 'title': '[유통 이슈] MCM x 독일 요하네스 본자이퍼 협업한 한정판 DJ 트렁크 전시 外'}, {'cnt': 31, 'description': "국내에서 주요 명품 브랜드 중 이같은 체험형 마케팅에 가장 먼저 나선 것은 '명품 중의 명품'으로 불리는 <b>에르메스</b>다. 2006년 플래그십 매장 '메종 <b>에르메스</b> 도산 파크'를 열면서 카페 마당을 운영 중이다. <b>에르메스</b>... ", 'link': 'https://n.news.naver.com/mnews/article/015/0004708179?sid=103', 'org_link': 'https://www.hankyung.com/life/article/202206032405g', 'pDate': '2022-06-07 10:46:00', 'title': "루이비통·구찌 레스토랑, 디올 카페까지 선보여…'예약전쟁' [오정민의 MZ담..."}, {'cnt': 32, 'description': '프랑스 3대 명품 ‘에루샤(<b>에르메스</b>, 루이비통, 샤넬)’가 지난해 국내에서 3조2000억원대 역대 최대... 전통적인 에루샤(<b>에르메스</b>, 루이비통, 샤넬) 브랜드가 아닌 아미(AMI), 르메르(Lemaire), 메종 마르지엘라(Maison... ', 'link': 'https://www.junggi.co.kr/article/articleView.html?no=28818', 'org_link': 'https://www.junggi.co.kr/article/articleView.html?no=28818', 'pDate': '2022-06-07 00:02:00', 'title': '명품 카테고리의 확장…뉴럭셔리 ‘럭비남’ 주목'}, {'cnt': 33, 'description': '있는 <b>에르메스</b> 뷰티 샤이니 립스틱은 수채화처럼 은은한 컬러가 섬세한 광택과 함께 입술 위에 피어오른다. 이게 바로 글로만 보던 ‘물먹립’이구나란 생각이 절로 드는 마무리감! ‘빤딱빤딱’한 울트라 샤인 광택으로... ', 'link': 'http://www.elle.co.kr/article/66702', 'org_link': 'http://www.elle.co.kr/article/66702', 'pDate': '2022-06-07 00:02:00', 'title': '글로시 파 vs 매트 파'}, {'cnt': 34, 'description': '한국지엠 직영 서비스센터는 이스타항공, 한국시세이도, 루이비통코리아, <b>에르메스</b>코리아, H&amp;M(헤네스앤모리츠) 등의 회사와 함께 직장어린이집 설치 의무 실태조사 불응 사업장 명단에 이름을 올렸다. 앞서... ', 'link': 'http://www.kihoilbo.co.kr/news/articleView.html?idxno=982511', 'org_link': 'http://www.kihoilbo.co.kr/news/articleView.html?idxno=982511', 'pDate': '2022-06-06 17:08:00', 'title': '한국지엠 직영 서비스센터 직장어린이집 설치 외면?'}, {'cnt': 35, 'description': '반면에 샤넬, <b>에르메스</b> 같은 브랜드는 사치품을 상징합니다. 나이키는 어떤 브랜드입니까? 벤츠와 페라리, 현대차 기아 브랜드는 어떤가요? 쿠팡과 배달의민족은? 브랜드 전문가가... ', 'link': 'https://n.news.naver.com/mnews/article/015/0004707906?sid=101', 'org_link': 'https://www.hankyung.com/news/article/2022060315731', 'pDate': '2022-06-06 15:34:00', 'title': "[커버스토리] 브랜드는 고객이 느끼는 '모든 것'"}, {'cnt': 36, 'description': '= 보통 사람들은 하나 갖기도 힘든 <b>에르메스</b> 버킨백을 세계에서 가장 많이 가진 것으로 알려진 여성의... 드레스룸은 마치 백화점 명품관을 옮겨 놓은 듯 명품들이 한가득이었다.특히 구하기도 힘든 <b>에르메스</b>의 버킨백을... ', 'link': 'https://www.insight.co.kr/news/398407', 'org_link': 'https://www.insight.co.kr/news/398407', 'pDate': '2022-06-06 15:16:00', 'title': "재벌 남편과 이혼 후 위자료로 매달 '4억' 받는 여성이 공개한 대저택 수준 (..."}, {'cnt': 37, 'description': '<b>에르메스</b>는 2006년 서울 도산공원 인근 플래그십 스토어에 ‘<b>에르메스</b> 카페 마당’이라는 이름의 카페를 열었다. 디올도 2015년 서울 청담동 플래그십 부티크 ‘하우스 오브 디올’에 루프톱 카페를 낸 바 있다. 다만... ', 'link': 'https://woman.donga.com/3/all/12/3418579/1', 'org_link': 'https://woman.donga.com/3/all/12/3418579/1', 'pDate': '2022-06-06 10:32:00', 'title': '[luxury] 구찌, 루이비통, 디올… 식도락 격전지가 된 명품 스토어'}, {'cnt': 38, 'description': '나이키, 아디다스, 삼성, 애플, 아마존, 구글, 코카콜라, 쿠팡, 배달의민족, 포드, 페라리, 현대, 샤넬, <b>에르메스</b>, 맥도날드, SK, 롯데…. 이 중에는 여러분이 당장 구매할 수 있는 브랜드도 있고, 나중에 어른이 되어서... ', 'link': 'https://n.news.naver.com/mnews/article/015/0004707854?sid=101', 'org_link': 'https://www.hankyung.com/economy/article/2022060320891', 'pDate': '2022-06-06 10:02:00', 'title': '[커버스토리] 20년 전 애플·아마존·구글·삼성은?…생명처럼 브랜드도 생겼...'}, {'cnt': 39, 'description': '오리베 #헤어제품의<b>에르메스</b> #향이좋은샴푸 오리베는 40년 이상 할리우드 셀럽들의 헤어스타일리스트 경력을 자랑하는 오리베 카날레스의 손길, 열정, 영혼 그리고 장인 정신을 담은 브랜드다. 각 제품은... ', 'link': 'http://woman.chosun.com/news/articleView.html?idxno=98763', 'org_link': 'http://woman.chosun.com/news/articleView.html?idxno=98763', 'pDate': '2022-06-06 08:02:00', 'title': '아는 사람은 찾아 쓰는 해외 뷰티 입소문템 ①'}, {'cnt': 40, 'description': '<b>에르메스</b>에서는 고객 한 명에게 같은 디자인의 가방은 연간 두 개까지만 팝니다. 신발과 패션주얼리 상품은 1인당 같은 모델을 하루에 2개까지만 살 수 있습니다. <b>에르메스</b>는 다이어리·담요·바구니 등 소품이나 작은... ', 'link': 'https://n.news.naver.com/mnews/article/015/0004707831?sid=103', 'org_link': 'https://www.hankyung.com/life/article/202206043820g', 'pDate': '2022-06-06 07:26:00', 'title': '&quot;샤넬백 사러 갔는데 판매거부 당했어요&quot;…이유 들어보니 [안혜원의 명품의 세...'}, {'cnt': 41, 'description': '5. 웨스턴 버클 벨트 39만7000원 러스트 무드 by 샌프란시스코마켓. 6. 실버 도금 버클 리버서블 벨트 가격 미정 <b>에르메스</b>. 7. 골드 메두사 비기 버클 벨트 69만원 베르사체.', 'link': 'http://www.esquirekorea.co.kr/article/66976', 'org_link': 'http://www.esquirekorea.co.kr/article/66976', 'pDate': '2022-06-06 00:02:00', 'title': '여름에 차기 좋은 버클이 예쁜 벨트'}, {'cnt': 42, 'description': "김건희 여사는 왜 수많은 명품 브랜드 중 <b>에르메스</b>나 샤넬, 루이비통이 아닌 '디올'을 선택했는지 대중의... 송 대표는 &quot;김 여사가 초고가 명품인 <b>에르메스</b>를 입었다고 하면 사회적 논란이 되었을 것&quot;이라며 &quot;자신에게... ", 'link': 'https://n.news.naver.com/mnews/article/008/0004754807?sid=103', 'org_link': 'http://news.mt.co.kr/mtview.php?no=2022060513272715490', 'pDate': '2022-06-05 15:16:00', 'title': "&quot;김건희 여사는 디올(Dior)을 입는다&quot;..퍼스트 레이디의 '품격'"}, {'cnt': 43, 'description': '예를 들어, <b>에르메스</b>의 가방을 구매하고 싶다면 이전에 티셔츠나 손수건 등 다른 제품을 몇 개라도 산 이력이 있다면 훨씬 쉽게 가방을 볼 수 있습니다. 매장이나 셀러에 따라 구매 이력이 없는 고객에겐 가방의 존재조차... ', 'link': 'https://n.news.naver.com/mnews/article/081/0003277904?sid=103', 'org_link': 'https://www.seoul.co.kr/news/newsView.php?id=20220605500026&wlog_tag3=naver', 'pDate': '2022-06-05 11:27:00', 'title': '쇼제품 판매 가능한데…노란색 타탄무늬 디올 신제품에 명품업계 ‘시끌’ [명...'}, {'cnt': 44, 'description': '<b>에르메스</b>의 나데주 바니 시뷸스키가 말하는 시적인 키 노트가 이번 시즌을 대표한다. “저 멀리 수평선이 펼쳐진다. 신비로운 광채로 반짝이는 실린더. 옐로, 바로 태양이다. 그녀는 새벽녘의 컬러를 투영한다. 황톳빛의... ', 'link': 'http://www.elle.co.kr/article/66699', 'org_link': 'http://www.elle.co.kr/article/66699', 'pDate': '2022-06-05 00:04:00', 'title': '이번 여름의 키 컬러는? 신비로운 다홍빛!'}, {'cnt': 45, 'description': '내 첫 명품 주얼리였던 <b>에르메스</b>의 브레이슬릿, 디자이너 브랜드 브릴피스의 볼 이어커프, 디자이너 브랜드 레끌라의 건축적인 반지는 매일같이 착용하는 진짜 ‘애정템’이다. ━ 각자의 역사를 보존해줄 수 있는 시계... ', 'link': 'http://www.harpersbazaar.co.kr/article/66757', 'org_link': 'http://www.harpersbazaar.co.kr/article/66757', 'pDate': '2022-06-05 00:02:00', 'title': "시계와 주얼리, '찐'마니아들은 어떤 제품을 착용할까?"}, {'cnt': 46, 'description': '(사진=크리스에프앤씨)제2의 파리게이츠인 ‘마스터바니’, 골프계의 <b>에르메스</b>를 표방하는 ‘세인트앤드류스’ 등의 매출도 지속 성장 중이다. 작년 기준 매출 순으로 보면 △파리게이츠(1134억원) △핑(997억원) △팬텀... ', 'link': 'https://n.news.naver.com/mnews/article/018/0005233756?sid=101', 'org_link': 'http://www.edaily.co.kr/news/newspath.asp?newsid=01341526632358440', 'pDate': '2022-06-04 11:16:00', 'title': '‘화재에도 잘나가’…크리스에프앤씨의 믿을 구석은[윤정훈의 생활주식]'}, {'cnt': 47, 'description': '국내에서 니치 향수 시장을 선도하고 있는 신세계인터내셔날도 딥디크, 산타마리아노베라, <b>에르메스</b> 퍼퓸 등 9개 니치 향수 브랜드 판권을 보유하고 있으며, 삼성물산 패션부문은 2022년 가을 시즌 톰브라운 향수·향초... ', 'link': 'https://www.viva100.com/main/view.php?key=20220602010000413', 'org_link': 'https://www.viva100.com/main/view.php?key=20220602010000413', 'pDate': '2022-06-04 09:04:00', 'title': '마스크 벗으니 날개단 ‘퍼퓸시장’…프리미엄 향수 무한 경쟁'}, {'cnt': 48, 'description': '명품 브랜드인 <b>에르메스</b>도 버섯 가죽 원단인 ‘실바니아’를 개발해 곧 가방을 출시할 예정이다. 쓸모 없다고 여겨진 물건이 심지어 명품으로 거듭나는 셈이다. 구찌는 목재 펄프 신소재로 만든 비건 가죽 운동화를... ', 'link': 'https://n.news.naver.com/mnews/article/011/0004061538?sid=101', 'org_link': 'https://www.sedaily.com/NewsView/2673PRXMAX', 'pDate': '2022-06-03 18:21:00', 'title': '쓰레기는 없다…지갑으로 변신한 선인장[지구용 리포트]'}, {'cnt': 49, 'description': '올 3월 말 기준 지수를 구성하는 주요 종목으로는 △루이비통(LVMH·8%) △<b>에르메스</b>(HRMS·6%) △에스티로더(EL·5%) 및 까르띠에·몽블랑 등을 보유한 △리치몬트그룹(CFR·8%), 구찌·입생로랑·보테가베네타 등의 △케링(PRTP... ', 'link': 'https://n.news.naver.com/mnews/article/011/0004061499?sid=101', 'org_link': 'https://www.sedaily.com/NewsView/2673Q4HQCG', 'pDate': '2022-06-03 17:33:00', 'title': '[ETF줌인] 명품 투자 ETF…면세점 매출 회복 수혜 기대'}, {'cnt': 50, 'description': '<b>에르메스</b>와 함께 떠나요. ‘여행자의 시간’이라고 이름 붙인 ‘아쏘 르 땅 보야쥬(Arceau le temps voyageur)’는 <b>에르메스</b>만의 독특한 상상의 세계로 우리를 초대한다. 시간 여행이 시작되면 다이얼에 변화가 생긴다. 12시... ', 'link': 'https://magazine.hankyung.com/money/article/202205248634c', 'org_link': 'https://magazine.hankyung.com/money/article/202205248634c', 'pDate': '2022-06-03 16:42:00', 'title': '[Must Have] 여행자의 시간'}, {'cnt': 51, 'descripti

In [31]:
data_title = []
data_description = []
for item in data:
    data_title.append(item['title'])
    data_description.append(item['description'])

data_df = pd.DataFrame({'title':data_title, 'description':data_description})

In [32]:
data_df.head()

,title,description
0,&quot;결혼식 교복이냐&quot; 굴욕 겪은 샤넬…또 가격 인상설 솔솔,<b>에르메스</b>와 롤렉스는 매년 한 차례 씩 가격을 인상해왔다. 일각에서는 리...
1,너도 나도 팔목에 스마트워치…결국 ‘이 브랜드’ 관심 끌었다 [명품톡+],"이전에도 삼성과 톰브라운, 애플과 <b>에르메스</b>의 스마트워치 협업 소식은 있..."
2,구찌·디올에 이어 세계 최초 루이비통 레스토랑까지... 왜 '코리아'일까,"루이비통 제공 <b>에르메스</b>, 구찌, 디올 등 콧대 높은 명품 브랜드들이 ..."
3,"[유통 이슈] 헨켈홈케어코리아 브레프-패스트파이브, ‘상쾌한 화장실 조성 캠...","또, <b>에르메스</b>, 구찌, 랑콤, 디올, 다이슨 등 명품 브랜드 방송의 메..."
4,"'10분 진료비가 9만원' 오은영 박사가 타고 다니는 차, 차원이 다른 수준이다","“가격에 입틀막” 오은영, <b>에르메스</b> VVIP 논란 이어 '초고가 명품 ..."

In [33]:
data_title

['&quot;결혼식 교복이냐&quot; 굴욕 겪은 샤넬…또 가격 인상설 솔솔',
 '너도 나도 팔목에 스마트워치…결국 ‘이 브랜드’ 관심 끌었다 [명품톡+]',
 "구찌·디올에 이어 세계 최초 루이비통 레스토랑까지... 왜 '코리아'일까",
 '[유통 이슈] 헨켈홈케어코리아 브레프-패스트파이브, ‘상쾌한 화장실 조성 캠...',
 "'10분 진료비가 9만원' 오은영 박사가 타고 다니는 차, 차원이 다른 수준이다",
 "패션업계가 '느림의 미학'에 빠진 이유",
 '모피로 덮인 <b>에르메스</b> 버킨백 NFT, 합법일까 위법일까[김윤희의 지식재산권 산...',
 '리바이스 “2027년까지 연 6~7% 성장…100억 달러 달성”',
 "600만원 디올백 대신 2만원 라떼…요즘 뜨는 '인증샷' 성지",
 "<b>에르메스</b>, 루이뷔통…'명품에 환장한 중국', 봉쇄 이후 보복소비",
 '샤넬 주얼리도 올랐다…평균 10% 가격 인상',
 '세 남자의 일탈 드라이브',
 '‘킴 카다시인과 도플갱어’ 24살 모델, “내가 카녜이 웨스트와 결별? 가짜뉴...',
 "정재일, 세계적 음악레이블 '데카'와 글로벌 계약",
 "30년 1위 자리 폴로에 내줬다…'토종 패션' 빈폴의 위기[박동휘의 컨슈머 리포...",
 "[뉴리테일 &amp; 더현대 ①] 유통 불모지 입성한 더현대서울, '취향 쪼개기'로 진...",
 '[Men’s Look] 셔츠 입기 좋은 지금',
 '쌓여가는 대중 브랜드 재고…美\xa0패션시장, 명품만 잘 팔린다',
 '[기획] 교촌 1991‧ GS25에 담긴 비밀은?',
 '<b>에르메스</b> 뷰티의 새로운 비전',
 '44살 카녜이 웨스트, ‘킴 카다시안 도플갱어’ 24살 여친과 5개월만에 결별[...',
 '트렌비, 명품 리셀 서비스 약 14만40000건, 총 거래액 약 1690억원 돌파',
 "'싱글맘' 박연수, <b>에르메스</b> 가방에 칼 댔다…&quot;세상 하나밖에 없어&quot;",
 '박연수, <b>에르메스</b>백 직접 리폼..&quot;세상에서 하나밖에 없어 소중&quot;',
 '[Who Is ?] 조현범 한국앤컴퍼니 대표이사 회장',
 '루이비통 의자 1.3억·소파 9천만원…&quot;백화점엔 없다&quot; 2030 몰려간 곳',
 '[특파원 칼럼] 긴자 거리의 100엔숍과 추락하는 소득/김진아 도쿄특파원',
 "리본즈, '론칭 10주년 기념' 고객 감사 이벤트 진행",
 '리본즈, ‘론칭 10주년 기념’ 고객 감사 이벤트 진행',
 '[유통 이슈] MCM x 독일 요하네스 본자이퍼 협업한 한정판 DJ 트렁크 전시 外',
 "루이비통·구찌 레스토랑, 디올 카페까지 선보여…'예약전쟁' [오정민의 MZ담...",
 '명품 카테고리의 확장…뉴럭셔리 ‘럭비남’ 주목',
 '글로시 파 vs 매트 파',
 '한국지엠 직영 서비스센터 직장어린이집 설치 외면?',
 "[커버스토리] 브랜드는 고객이 느끼는 '모든 것'",
 "재벌 남편과 이혼 후 위자료로 매달 '4억' 받는 여성이 공개한 대저택 수준 (...",
 '[luxury] 구찌, 루이비통, 디올… 식도락 격전지가 된 명품 스토어',
 '[커버스토리] 20년 전 애플·아마존·구글·삼성은?…생명처럼 브랜드도 생겼...',
 '아는 사람은 찾아 쓰는 해외 뷰티 입소문템 ①',
 '&quot;샤넬백 사러 갔는데 판매거부 당했어요&quot;…이유 들어보니 [안혜원의 명품의 세...',
 '여름에 차기 좋은 버클이 예쁜 벨트',
 "&quot;김건희 여사는 디올(Dior)을 입는다&quot;..퍼스트 레이디의 '품격'",
 '쇼제품 판매 가능한데…노란색 타탄무늬 디올 신제품에 명품업계 ‘시끌’ [명...',
 '이번 여름의 키 컬러는? 신비로운 다홍빛!',
 "시계와 주얼리, '찐'마니아들은 어떤 제품을 착용할까?",
 '‘화재에도 잘나가’…크리스에프앤씨의 믿을 구석은[윤정훈의 생활주식]',
 '마스크 벗으니 날개단 ‘퍼퓸시장’…프리미엄 향수 무한 경쟁',
 '쓰레기는 없다…지갑으로 변신한 선인장[지구용 리포트]',
 '[ETF줌인] 명품 투자 ETF…면세점 매출 회복 수혜 기대',
 '[Must Have] 여행자의 시간',
 '신영균예술문화재단, 제21회 필름게이트 제작지원작 5편 선정...총 5천만 원 ...',
 "'핫플' 스키주 팝업스토어 가보니…스키즈 '글로벌 대세' 맞네[MK현장]",
 '100만원 이내로 명품 선물하기',
 '美 패션 시장 난기류…‘명품, 하이패션만 잘 팔린다’',
 'Find Dining | 나를 찾는 한 끼',
 '구찌, 반지로 심박수 측정···헬스케어 시장 노크',
 "'두 달 봉쇄 끝,' 中 상하이 명품매장 앞에 장사진",
 "&quot;'심쿵'하는지 체크&quot;…구찌 '118만원' 스마트 반지 판다",
 '[르포] 앱 밖으로 나온 온라인플랫폼…‘각양각색’ 매장 가보니',
 '韓 패션시장, 명품 식민지인가? 코로나 팬데믹 속 8.6조 규모 급팽창',
 'NO.38 지금 가장 핫한 시계 브랜드!',
 '[Who Is ?] 차정호 신세계 백화점부문 기획전략본부장 사장',
 '이집 유전자 무섭네…이현이, 가족 모두가 연예인 비주얼',
 '신동빈, 피아노 연주에 푹 빠진 까닭은[재계 블로그]',
 "&quot;10초에 하나씩 팔리는 우유&quot;…우유 업계 뒤흔든 '이것' 정체는?",
 '또 오른 호텔 빙수 가격…스몰 럭셔리·메뉴 다양화로 승부',
 '올해 여름 유행은 명품 브랜드 하와이안 셔츠 8',
 '서머 슈즈 스타일링 ② 글래디에이터 &amp; 슬라이드',
 '립 아이 베이스 색조 메이크업부터 쿠션, 썬크림, 자차 등 6월의 신상 뷰티 신...',
 "&quot;우리 이제 결혼해요&quot;…예물 반지·프로포즈 가방 수요 '쑥'",
 "더현대 성공 공식은 'MZ세대'…스키주 팝업스토어 가보니(영상)",
 "[현장르포] 프랑스 문화를 느끼는 퍼퓸바…한섬, '니치 향수' 시장 공략",
 '신세계百 경기점 재단장 완료…전운 감도는 경기남부',
 '직장어린이집 설치의무 외면 사업장 “꼼짝마”',
 "직장어린이집 설치의무 외면한 사업장 '꼼짝마'",
 '[STYLE] FRAGRANCES | SCENTS OF SUMMER',
 '유통기업 등 42곳, 직장 어린이집 설치 의무 위반',
 '머스트잇 매거진 Ep90, 공간 정리를 끝장 내줄 각종 라이프 툴',
 '직장어린이집 설치 비용 아까워 과태료 내는 기업들',
 '유럽증시, 중국의 봉쇄조치 완화 기대감에 일제히 올라…영국 0.19%-독일 0.7...',
 "일상회복 분위기에 유통가 '봄바람' 분다",
 '[유럽증시] 中 봉쇄완화 기대에 상승...베어마켓 랠리 경계감 여전',
 'SSG닷컴·코스트코...직장어린이집 설치 의무 위반 기업 공개',
 '직장 어린이집 설치 의무 위반 사업장 명단 공개',
 "사내 어린이집 '나 몰라라'…버티는 회사들 공개한 정부",
 '경동·코스트코 ‘직장어린이집’ 나 몰라라',
 '&quot;SSG닷컴·코스트코 등 직장어린이집 설치 의무 불이행&quot;',
 "'명품따라 강남간다'…백화점 3사 MD 강남에 모였다",
 '코스트코 등 직장어린이집 설치의무 위반',
 '경동·<b>에르메스</b>·코스트코 등 직장 어린이집 설치 의무 위반',
 '코스트코코리아·안진회계법인 등 42곳…‘직장어린이집 설치 의무’ 외면',
 '中 럭셔리 상징, 봉쇄 한 달 만에 문 열었다',
 '직원 복지는 짝퉁?…어린이집 설치 의무 위반 사업장에 루이비통',
 '코스트코, 오스템임플란트 등 직장어린이집 설치 의무 안 지켜',
 '코스트코‧SSG닷컴‧대형회계법인 등 직장어린이집 설치의무 위반',
 '복지부·노동부, 직장어린이집 설치 의무 무시한 대기업 등 공개',
 "안진·한영회계법인 3년 넘게 직장어린이집 '모르쇠'...내년부턴 과태료",
 '코스트코코리아·SSG닷컴 등 직장 어린이집 설치 의무 안 지켜',
 '직장어린이집 설치의무 미이행·조사 불응 41개 사업장 명단은?',
 'SSG닷컴 등 직장 어린이집 설치 의무 미준수',
 'SSG닷컴·코스트코·대형 회계법인…직장 어린이집 설치 의무 안 지켜',
 "직장어린이집 설치율 90.9%…루이비통 등 다국적 기업들은 '조사 불응'",
 '대형 회계법인·유통업체 등 직장 어린이집 설치 의무 안 지켜',
 '유통업체·회계법인 등 42곳, 직장어린이집 미설치',
 '전세계 중앙은행, 최근 3개월간 기준금리 60회 이상 인상',
 '서머 슈즈 스타일링 ① 미니멀 로퍼 &amp; 스트랩 샌들',
 '판이 바뀐 럭셔리 시장…MZ세대 주도 ‘뉴럭셔리’ 뜬다',
 '&quot;친환경도 힙하게&quot;…트렌디한 리사이클링 패션 아이템 인기',
 '[기자수첩] 年 6번 가격 올린 샤넬 “고객도 이젠 등 돌립니다”',
 '가수 현아를 ‘패션퀸’으로 만든 그 디자이너…로사 김 로사케이 대표',
 "럭셔리판다, 롯데호텔월드 협업 '럭셔리 라이프 패키지' 출시",
 '‘취임 반년’ 정준호 롯데百 대표, ‘강남 1등 백화점’ 만들기 드라이브',
 '[김기자의 금요외식회] 루이비통에서 밥 먹고 디올에서 커피 한 잔…업그레이...',
 "[기자수첩] 오픈런 대신 행사장 매대 올라온 명품백, '합리적 가격의 명품'도...",
 '&quot;<b>에르메스</b> 그릇, 대기만 6개월&quot;…명품그릇 불티난다',
 "'명품 건기식' 오쏘몰, 가격만 명품?",
 '&quot;마스크 벗고 맡으세요&quot; 커지는 니치향수 시장',
 "&quot;돈 있어도 못 사네&quot;...명품 브랜드 샤넬 '1인당 구매량 제한' 정책 확대",
 "럭셔리판다, 롯데호텔월드 협업 '럭셔리 라이프 패키지' 출시",
 '[르포]&quot;BTS가 즐겨 입는 브랜드는?&quot;..편집숍엔 트렌드가 있다',
 '패션 에디터가 선별한 올해의 여름 향수 14',
 "신세계백화점, 즐기고 체험하고 쇼핑까지…MZ '뷰티놀이터' 떠오른 시코르",
 "'캐시미어를 두른 늑대'…우리가 욕망하는 모든 것, 그의 손에 지배된다",
 '샤넬, 1인당 구매제한 확대 가능성↑…7월 추가 가격 인상 언급',
 '여름휴가 대목 노리는 롯데·신라·신세계·현대百면세점…‘누가 웃을까’',
 '샤넬, 1인당 구매제한 확대 계획...&quot;품목·국가 확대 시행&quot;',
 '삼정KPMG &quot;글로벌 럭셔리 시장, V자 반등…전년대비 13.5% ↑&quot;',
 '콧대 높은 샤넬, 1인당 구매제한 전세계 확대하나',
 "한국만 '월드워런티' 쏙 뺀 샤넬…'배짱 영업' 어디까지",
 '샤넬 1인당 구매제한 확대하나…“7월 가격 인상도 검토”',
 "한섬 '조향사' 앞세워 니치향수 시장 공략, 김민덕 뷰티사업 확장",
 '샤넬백 또 오를까…&quot;7월 중 가격인상 나설 수도&quot;',
 "삼정KPMG &quot;급변하는 럭셔리산업…'뉴럭셔리' 트렌드 주목&quot;",
 '韓 플랩백 인당구매 제한 둔 샤넬 &quot;품목·국가 확대 가능&quot;',
 '샤넬 1인당 구매제한 확대하나…&quot;품목·국가 확대 시행 가능&quot;',
 "하림펫푸드, '더리얼 로우' 출시 기념 '카이 트월리' 프로모션",
 "'7606억' 덩치 커진 시장…패션가, 니치 향수로 유혹한다",
 "명품 브랜드 '에루샤' 가고 '아르메' 뜬다...한국, 글로벌 명품시장 톱10",
 '삼정KPMG &quot;지난해 글로벌 럭셔리 시장 2942억달러…한국은 세계 10위&quot;',
 '하림펫푸드 더리얼 로우, 카이와 맞손…멍냥이도 트윌리로 멋낸다',
 "한동훈, 빈티지 시계에 나토스트랩...시계 마니아들 '관심'",
 '작년 글로벌 럭셔리 시장 2942억달러…한국시장 세계 10위 규모',
 '[리얼푸드]하림펫푸드, ‘더리얼 로우’ 강아지사료와 패션브랜드 콜라보',
 'MZ세대, 럭셔리 시장 핵심고객으로 부상…&quot;NFT·3D 디지털 소비경험 주목&quot;',
 "MZ세대 중심으로 '보복소비' 증가.. '신(新)명품' 시장 주목",
 'MZ세대 럭셔리 주력층 부상…작년 국내 명품시장 30% 성장',
 "'럭셔리가 뜬다' 국내 명품시장 규모 세계 10위…2024년 8.8조로 확대",
 "MZ·온라인·리세일·디지털..'뉴럭셔리' 부상",
 '머스트잇 매거진 Ep89, 백진희 페사드 크리에이티브 디렉터가 사랑하는 브랜드',
 '<b>에르메스</b>가 이런 것도 만들어?',
 '&quot;NFT는 디지털 <b>에르메스</b>…제3의 물결 대비를&quot;',
 '롯데百 VIP행사라더니 난장판… 불만 폭주',
 '이진욱과 이연희에게 ‘결혼’이란',
 'Lovely Beauty Item',
 '선과 면의 마법',
 "'화려함 뒤 짙은 그늘' 명품 플랫폼, 쿠팡 따라잡기 '아직'",
 '마스크 벗자 날개 단 향수',
 "1000만원 넘게 주고 샀는데…샤넬백, AS 맡겼다가 '황당'",
 '[BOOKS] 사라고 하지 않으면서도 사게 만드는 비결',
 '[Interview] ‘더현대서울 인사이트’ 낸 김난도 서울대 소비자학과 교수 | “...',
 '20~40만원대 니치 향수, 마스크 벗고 더 팔렸다... 스몰럭셔리 지향하는 MZ세...',
 '롯데호텔월드 X 럭셔리판다 콜라보 명품업계 최초 명품 룸서비스 출시',
 '이부진-고소영의 특별한 인연, 어떤 사이?',
 "삼성 이부진과 머리 맞대고 '투샷' 공개하며 '황금 인맥' 인증한 고소영",
 '고소영·이부진 ‘워킹맘’ 투샷…“위로되고 힘 얻는 시간”',
 '샤넬 롤렉스 신품 사서 중고로 팔아 돈벌기, 이젠 끝났다',
 "[스타 스타일] '별똥별' 이성경 패션",
 "박정호 부회장, 어떻게 SK하이닉스에 'SKT DNA' 이식했을까",
 '[추천템] 플랜트 패턴 리빙 아이템',
 '[유통토요판] 주춤한 오픈런, 한풀 꺾인 샤넬 인기',
 "결혼기념일에 엘리베이터 '꽃'으로 가득 채워 아내 위한 깜짝 이벤트 해준 사...",
 '&quot;분양 받으시고 자동차·명품백 받아가세요&quot; 부동산 경품 어디까지',
 '[안병익의 식신 맛집] 오늘 디너는 구찌? 루이비통? 명품이 만든 럭셔리 레스...',
 '김건희 ‘5만원 안경’ 사진 속 ‘노란 휴지’ 고가 논란… “‘서민 코스프레...',
 '“샤넬백도 룸서비스로”…럭셔리판다, 롯데호텔 월드와 ‘럭셔리 라이프’ 상...',
 '황교익 &quot;김건희 여사, 안경은 5만원인데 휴지는 7만원?&quot;…실제 가격 살펴보니',
 '[비바100] 내 생애 마지막 음식은 바로 이것!',
 "김건희, 7만원 노란휴지 '논란'…강신업 &quot;내돈내산인데 무슨 상관&quot;",
 '여행사 사무실이 강남 <b>에르메스</b> 건물에?',
 "김건희 여사 쓰는 '휴지'가 7만원?…실제 가격 보니",
 '초현실적인 테이블웨어 브랜드, 고하 월드의 탄생',
 '5만원대 안경보다 더 화제 된 노란 휴지… 황교익 “‘서민 코스프레’ 딱 걸...',
 '유통가, 완벽한 리오프닝 맞아...리뉴얼·체험형 매장 오픈 잇달아',
 '“김건희 휴지는 7만원 딱 걸렸네” 황교익 주장, 사실일까?',
 "김건희 여사 '고가' 휴지 논란…실제 가격 얼마?",
 '황교익 &quot;김건희, 안경은 5만원인데 휴지는 7만원? 서민 코스프레 딱 걸려&quot;',
 '안경 5만원인데 휴지는 7만원?...황교익 “김건희 여사, 서민 코스프레 딱 걸...',
 '김건희 ‘노랑 휴지’ 논란…황교익 “서민 코스프레”-강신업 “유치하다”',
 "&quot;가방 비싸니 주스라도 마셔볼까&quot;…디올 카페 '예약전쟁'",
 "'태국재벌♥'신주아, 컵도 아무거나 안써..<b>에르메스</b> 컵 인증 &quot;행복&quot;",
 '황교익 &quot;김건희 안경 5만원, 휴지는 7만원&quot; 건희사랑 &quot;딱 유치&quot;',
 '김건희 노란휴지 시끌…황교익 &quot;안경만 서민&quot; 강신업 &quot;법카는 안썼다&quot;',
 '백화점 앞서고, 면세점 따라가고...현대백화점 2Q도 맑다',
 '놓치지 말아야 할 5월의 뷰티 뉴스',
 '5월은 계절의 여왕, 견(silk)은 섬유의 여왕',
 'F&amp;B에 빠진 명품 브랜드…구찌·디올서 미식도 즐기고 명품도 사고',
 '[창간12년/엔데믹 유통업계③] “명품 끌고 패션 밀고”..백화점, 손님맞이 ‘...',
 "[격변의 20년, 기업에서 미래를 찾다] '신세계 유니버스' 따로, 또 같이 걸은...",
 "[르포]대기줄 달랑 30명…'오픈런' 썰렁해진 샤넬의 굴욕",
 '바샤커피는 어떻게 커피계의 <b>에르메스</b>가 될 수 있었나?',
 '영화 대본 NFT 출시한 타란티노 감독, 미라맥스로부터 저작권 및 상표권 침해...',
 '[최앤리의 스타트업×법] #2 NFT를 구매해도 소유자가 될 수 없다고요?',
 '<b>에르메스</b>의 여행용 슈트 케이스',
 'The History of Hermès Jewelry',
 '이동가방 400만원·식기 150만원… 패션계 ‘펫셔리’ 바람 분다 [급성장하는...',
 '화장 좀 해볼까…시코르 강남역점, 5년만에 리뉴얼 오픈',
 '온라인 힘주던 시코르, 다시 오프라인 강화 나선다',
 '[급성장하는 펫코노미 시장(中)] 이동가방 400만원·식기 150만원… 패션계 ‘...',
 '&lt;딜링룸 백브리핑&gt; 美물가급등지역 일부 둔화…동부 연안은 그대로',
 '[오늘의 장바구니] 제타플렉스·시코르·쿠쿠·위메프 외',
 '[현장스케치] 주체적이고 독창적인 삶과 예술을 만드는 여성들, 롯데갤러리 동...',
 '“2026년까지 성장세” 엔데믹…여행 가방이 뜬다 [명품톡+]',
 "신세계百 뷰티편집숍 '시코르' MZ세대 놀이터 변신",
 '‘중고품 거래 시장’ 골드러시 시대 열렸다',
 '트레져러, 중고 명품숍 볼트제로 가로수길에 안착',
 "시코르 플래그립 스토어 강남역점, 'MZ세대 놀이터' 전환",
 "시코르 강남역점 새단장…MZ세대 취향 '정조준'",
 '시코르 강남역점, 5년 만에 리뉴얼 오픈…체험형 콘텐츠로 초점',
 '시코르 강남역점 리뉴얼 오픈… MZ세대 놀이터로 확 바뀐다',
 '신세계 시코르 강남역점, 5년만에 재단장…&quot;MZ세대 놀이터로 재탄생&quot;',
 '러시아-우크라이나 전쟁 후…럭셔리 브랜드, 설 곳 잃었을까 [명품톡+]',
 "잘나가는 아웃도어 브랜드, 한국 고객은 '봉'…쥐꼬리 기부금 여전",
 '시코르 강남역점, 5년 만에 리뉴얼… &quot;MZ세대 놀이터로 변신&quot;',
 '시코르 강남점 5년만에 리뉴얼···MZ세대 놀이터로 확 바뀐다',
 '신세계 시코르 강남역점 5년만에 재단장…&quot;MZ세대 놀이터로&quot;',
 '시코르 강남역점, MZ세대 놀이터로 변신…체험형 콘텐츠 선봬',
 '시코르 &quot;MZ세대 놀이터 만든다&quot;...강남역점 리뉴얼 개장',
 "[반구대] '100엔 회전 초밥'",
 '&quot;강세장 관점 버려라…수익률은 낮아지고 변동성만 커진다&quot;',
 '테크기업이 만든 명품 리셀숍 ‘볼트제로’ 오픈',
 '<b>에르메스</b> 재단이 선보이는 기묘한 심층 여행사',
 '야옹이 작가, <b>에르메스</b>백 들고 럭셔리 호텔..연예인보다 더 연예인 같네',
 '[준명품 보고서] 잘나가던 MCM 주춤한 이유는',
 '[테스트] 부드럽고 향기로운 보디 오일',
 '한그릇 8만3000원짜리 빙수 드시겠습니까?',
 '[천자 칼럼] 샤넬의 굴욕',
 '[데스크칼럼] 어떤 의자에 앉아계시나요?',
 "아직도 안해봤니? 아이보다 '엄빠'가 더 즐거운 '럭셔리 차박'",
 "가죽염색도 배운 <b>에르메스</b> 6대손…은행 관두고 '위기의 家業' 지키다",
 '&quot;변함없이 高高한 에·루·샤&quot;…보복소비 업고 실적 날았다',
 '“‘에·루·샤’ 매월 7만9000원에…명품 체험 비즈니스로 승부”',
 '손담비 &quot;좋은 날에 터무니없는 말…&quot; 절친 손절설 직접 해명',
 '&quot;힙하다&quot; vs &quot;짝퉁인줄&quot;…구찌 손잡은 아디다스 어떻길래',
 '[테스트] 부드럽고 향기로운 보디로션',
 '12만 원 애프터눈 티 세트부터, 8만 원 대 망고 빙수까지, 디올, <b>에르메스</b>, 신...',
 '로즈데이를 맞이해 준비한 장미를 닮은 패션 스타일링',
 "&quot;돈 있어도 못 산다&quot;…'최고 명품' 등극한 <b>에르메스</b> 가문의 비결은",
 '&quot;해외여행 대신 명품 산다&quot; 작년 실적 잔치한 명품업계…올해는?',
 '1700만원 디올 러닝머신 진짜 팔렸다…별별 명품 다 있네',
 '‘킴 카다시안과 도플갱어’ 24살 채니 존스, 손목에 카녜이 웨스트 문신 새겨...',
 '가볍게 들고 다니기 좋은 캔버스 백 추천',
 '<b>에르메스</b> 백 든 정용진 아내 한지희씨, 故구자학 회장 빈소 조문',
 "&quot;흥분해서 현금으로&quot;...채정안, 천만 원대 명품백 구입 일화 '깜짝' [종합]",
 '현대백화점면세점 적자폭 다시 확대, 명품 브랜드 리뉴얼로 반등 노려',
 '리셀시장서 치솟던 롤렉스값 16% 급락…&quot;이젠 명품보다 해외여행&quot;',
 "금융위 조각투자 가이드라인 의미…&quot;'몰라서 등록 못했다' 안봐준다&quot;",
 "골프존, 혜택이 와르르… '하트팡팡 선물팡팡' 가정의 달 이벤트",
 '당구 여제 차유람, 국민의힘 영입.... 차유람은 누구? | 남편 이지성이 작년 ...',
 '지갑 얇아진 일본… 명품거리에 ‘300엔숍’이 생겼다',
 "백화점 3사, '리테일테라피' 효과 덕에 1분기 실적 '성장'",
 '중고명품 경매중개 ‘턴백’, 투자 유치',
 '박재범이 소주를 냈다고? 셀러브리티의 술들',
 '2024 올림픽 앞둔 佛 파리, 샹젤리제 새 단장 나선다',
 '아르케스파, 전 직원 대상 럭셔리 서비스 및 CS 교육 실시',
 '[유통 단신] 다이소·골프존·스타벅스·GS25 外',
 '백화점업계 빅3, 리오프닝에 실적 함박웃음…골프·패션 호조',
 "운동·시간 관리부터 패션 효과까지…20대 필수품된 '스마트워치'",
 '&quot;성숙한 시계 애호가 많은 한국은 중요한 국가&quot;',
 "'재벌2세♥' 박현선, 명품백 들고 럭셔리 호텔 行..심진화와 점심 데이트",
 '359만원 반려견 가방 뭐길래…<b>에르메스</b> VIP도 없어서 못산다',
 "'♥재벌 2세' 박현선, <b>에르메스</b>백 들고 럭셔리 호텔行..심진화와 데이트",
 "골프존, 고객 친화 강화..'가정의 달' 3천만원 혜택 쏜다",
 '5월 가정의 달, 선물수요 겨냥한 유통가 움직임 활발',
 '줄 서서 먹던 호텔 망고빙수…&quot;이젠 DIY로 즐겨요&quot;',
 "골프존, '하트팡팡 선물팡팡' 이벤트 진행··총 3천만원 상당 혜택",
 '모스크바 내 명품숍 대거 철수…우크라 침공 후 수백 개 폐점',
 '필웨이, 중고명품 최대 55% 할인 온오프라인 동시 진행',
 '‘전통=일류’ 엔데믹에도 통할 럭셔리의 팬데믹 전략 [명품톡+]',
 "중고명품 경매중개 플랫폼 '턴백' 추가 투자 유치\xa0",
 '명품 선물 이제 카톡으로 보낸다...&quot;지난해 명품 거래액 전년비 80%↑&quot;',
 "골프존, '하트팡팡 선물팡팡' 이벤트 진행…총 3000만원 상당 혜택",
 "골프존, 가정의 달 맞아 '하트팡팡 선물팡팡' 이벤트",
 '필웨이, 중고명품 최대 55% 할인전 진행…“샤넬 클래식 미듐 할인”',
 "골프존, '하트팡팡 선물팡팡' 이벤트 진행…총 3천만원 상당 혜택",
 '필웨이, 중고명품 온·오프라인 동시 최대 55% 할인전 개최',
 "골프존, 가정의 달 맞아 60개 골프장서 '하트팡팡 선물팡팡' 이벤트",
 '&quot;현대백화점, 하반기부터 전 사업 턴어라운드 기대&quot;-미래에셋證',
 '&quot;8만3000원 호텔 애플망고빙수, 집에서 만들었더니…&quot; [이미경의 인사이트]',
 "'갓파더' 김숙, 조나단에 명품지갑 깜짝 선물 &quot;오다 주웠다&quot;(종합)",
 '번스타인 &quot;인플레이션기 가격 결정력있는 회사 주목&quot;',
 "[신설상가] 읍내동 '스노우피크 당진점'캠핑계의 <b>에르메스</b> '스노우피크'",
 '[인포그래픽] SNS ‘인증샷’ 필수, 이색 명품 브랜드 공간 총정리',
 "[단독] '벨기에의 <b>에르메스</b>' 델보, 1000만원대 백 합류…평균 10% 가격 인상",
 "[#꿀신상#꿀혜택] 깨끗한나라 '노담'·마이리얼트립-한진관광 'MOU'·농심켈로...",
 '다시 유행이 돌아오는 그 때 그 시절 복고 패션',
 '‘명품 불패’ 한국으로…온라인 직진출 속도낸다 [언박싱]',
 "[이슈] 3대 백화점 명품 판매 승자는?... 매출은 '롯데' 신장률은 '신세계'",
 '번스타인 &quot;인플레 대응할 가격 결정력 있는 기업 찾아야&quot;',
 '글로벌 명품, 한국 온라인 직진출 속도',
 '필웨이, 5x5 중고명품 할인전 진행',
 '필웨이, 중고명품 최대 55% 할인전',
 '필웨이, 중고명품 최대 55% 할인전 진행',
 '“샤넬 클래식 미듐 할인” 필웨이, 중고명품 최대 55% 할인',
 '[유통 이슈] 프레시지, 양대창 맛집 ‘연타발 밀키트’ 출시 外',
 '엑스클로젯, 중고명품 상반기 시즌오프...대 300만원 할인',
 '[Who Is ?] 이부진 호텔신라 대표이사 사장',
 '포도껍질·버섯·선인장으로 가죽 만든다고?…‘비건’ 패션은 진화중',
 '새로운 디렉터와 함께 전환점을 맞은 브랜드 4',
 '콧대 높은 <b>에르메스</b>·샤넬도 고개 숙이는 VIP들은 누구?',
 '[기자수첩] 보복 소비 열풍, 아이들 명품 사랑으로 이어질까 우려',
 '[아침브리핑] 주말 사이 무슨 일? 내 비트코인 내놔!',
 '[르포]구찌·꼼데가르송·띠어리…한남동이 명품거리 된 이유',
 '‘터너상’ 佛미술가 국내 개인전',
 '<b>에르메스</b>의 여성복 아티스틱 디렉터의 이야기가 궁금하다면?',
 '루이뷔통·<b>에르메스</b> 담았다… 명품, 사지말고 투자하세요 [이런 펀드 어때요?...',
 "'에루샤'보다 구찌·프라다 찾는 MZ세대..그 이유는",
 '[단독]한국서 떼돈 번 루이비통…주얼리 단독매장 낸다',
 "명품, 줄 서서 사는 것 이해 안돼…카톡 등 비대면 소비 여전히 '활황'",
 '시몬스 침대, 가정의달 맞아 숙면 선물 추천',
 '&quot;롤렉스 시계 구해줄게&quot;…1억원 뜯어낸 40대, 결국',
 '러시아 우크라이나 전쟁에 대한 패션 브랜드 하우스의 태도',
 '반클리프도, 디올도… &quot;우린 카카오톡으로 간다&quot;',
 '“명품시계 대신 구매해주겠다” 거액 뜯어낸 40대 ‘철창행’',
 "'희귀템' 롤렉스 구해준다며…1억원 뜯어낸 40대 징역형",
 '\ufeff<b>에르메스</b>로 본 코인의 성공학',
 'HERMS H08',
 '박은지, LA서도 수천만원 <b>에르메스</b>백+샤넬 신발..럭셔리 끝판왕',
 '뜨거운 명품 플랫폼 시장…‘머·트·발’ 중 최종승자는 누구?',
 '‘한끼에 23만원’ 브랜드 보고 간다?...BTS와도 인연 있는 루이비통 [명품 이...',
 '&quot;라이프스타일을 팝니다&quot;…소비자 생활 파고드는 유통가',
 '회식? 엔데믹?…IT 스타트업 “재택이 일상이죠”',
 '그곳에서 무슨 일이? 워치스 앤 원더스 2022 리뷰 (2)',
 "루이비통 구찌 '패션 맛집' 궁금해서 갔다가 '찐 맛집' 찾았다 [핫 플레이스]",
 '[머니 뭐니] 명품은 할인 하지 않는다…카드 포인트 찾아 삼만리',
 '중고 그랜저도 울고 갈 우리 아들 첫 차, 알고 보니…',
 '그곳에서 무슨 일이? 워치스 앤 원더스 2022 리뷰 (1)',
 '워치스앤원더스 2022에서 만난 <b>에르메스</b> 워치',
 '印 릴라이언스, 축구장 10개 크기 명품 쇼핑몰 건립',
 "시몬스 침대, &quot;'가정의 달', 숙면 제품 선물하세요&quot;",
 '놓치지 말아야할 5월의 트렌드 뉴스',
 '‘커피계 <b>에르메스</b>’ 오픈런 부르는 싱가포르 명품 커피전문점 (톡파원25시)',
 "샤넬 대신 스타벅스 넣었다…AK플라자 '편한 백화점' 전략 먹힐까",
 '발렌시아가, 아르마니도 함께한 #StandWithUkraine',
 "'톡파원 25시' 커피계 <b>에르메스</b> 싱가포르 카페→각국의 어린이날 모습은?",
 '이찬원 놀라게 한 싱가포르 창이공항ㆍ카페ㆍ야경 명소(톡파원 25시)',
 "'톡파원25시' 이찬원, 타일러와 어린이날 논쟁... 결과는?",
 "'미국 어린이날 있나? 없나?' 이찬원 vs 타일러 입씨름",
 "[시계한국474] '2022 멧갈라'…스타들은 어떤 시계를 착용했나?",
 "'톡파원25시' 이찬원, 타일러와 어린이날 논쟁.. 결말은?",
 "'톡파원 25시' 창이 공항투어로 시작하는 싱가포르 여행, 엄격한 법 제도 소개",
 '&quot;명품만 잘 나가는게 아니네&quot;…자라 H&amp;M도 매출 확 늘었다',
 '[이슈크래커] ‘기울어진 운동장?’...증시와 명품의 공통점',
 '&quot;명품 감정, 최소 3년 돼야 <b>에르메스</b> 만질 수 있죠&quot;',
 '&quot;가격 인상 예정이니 추가금 더 내라&quot;… 명품업계, 배짱영업 논란',
 '시몬스 침대, 가정의 달 맞아 숙면 선물 추천',
 '&quot;가족에게 숙면을 선물하세요&quot;…시몬스 침대, 가정의 달 맞아 아이템 추천',
 '시몬스 침대, 가정의 달 맞아 모바일로 간편하게 선물하기 추천',
 "'톡파원25시' 이찬원 vs. 타일러...美 어린이날 유무 논쟁 후끈",
 "'톡파원 25시' 이찬원 VS 타일러, 어린이날 100주년 기념 '세계의 어린이' 특...",
 '강남서 힘 못 쓰던 롯데百, ‘신세계맨’ 정준호 매직 개봉박두!',
 '시몬스 침대, 가정의 달 맞아 숙면 선물 추천',
 "'톡파원25시' 이찬원, 타일러와 어린이날 논쟁!...그 결말은?",
 "이찬원vs타일러, '톡파원 25시'서 별안간 논쟁…왜?",
 '‘톡파원 25시’ 美 어린이날 있나? 이찬원 vs 타일러 후끈 논쟁[오늘TV]',
 '‘찬또위키’ 이찬원vs‘박사님’ 타일러의 어린이날 논쟁 후끈 (톡파원 25시...',
 "'톡파원25시' 이찬원vs타일러, 어린이날 논쟁…승자는?",
 '‘찬또위키’ 이찬원vs‘박사님’ 타일러, 어린이날 논쟁..결말은?(‘톡파원’...',
 "'한국 첫 개인전' 매즈 크리스텐센 vs 올리버 비어",
 '명품 업계, 온라인 직접 판매 강화',
 "화장품부터 패션까지 '비건'이 대세...친환경은 &quot;글쎄&quot;",
 '팬데믹 2021년 4월, 앤데믹 2022년 4월…유통가 이렇게 변했다',
 '[5월은 선물의달] 카카오, 명품부터 이색 선물까지... 모금 캠페인도 진행',
 '5월에 볼만한 전시 셋.',
 '개관도 안 한 놀이동산 통째로 빌려 직원들 놀게 한 이 기업',
 "어린이날 맞이 '통 큰' 복지. SK하이닉스...레고랜드 통 대관",
 '테라로사 커피: 세상에, 700억을 투자받은 카페가 있다고?!',
 '&quot;지상에 W컨셉 지하에 버버리&quot; 백화점 고정관념 깨다',
 "S&amp;P500, 4개월간 13% 이상 하락…83년만에 '최악'",
 '플라워 원피스 스타일리시하게 입는 법 ②',
 '여행의 시작, 신상 슈트케이스',
 '호모럭셔리쿠스, 한국인의 명품사랑…코로나19‧가격인상 뚫고 6조원어치 사다',
 '“5000만원 시계를 카톡 선물로?”… 명품에 꽂힌 카카오·네이버',
 "'이대 출신' 이현이·신임 검사 남동생, 피지컬→브레인 난리났네 난리났어 [...",
 '“디올 패션쇼에 과잠이?”...소비자心 잡기 위한 명품 업체들의 색다른 행보',
 "개인취향 저격…패션업계, '니치 향수' 시장 판 키운다",
 "디올 유아차, <b>에르메스</b> 턱받이 없어서 못산다…아동도 '명품사랑'",
 '카카오, 가정의 달 쇼핑 기획전 오픈',
 '이현이, 검사된 훈남 남동생 공개‥이지혜 “브레인 가족” 감탄',
 "도심 속 온실 '디올 성수' 직접 가보니…'핫플 예약'",
 '구찌·샤넬 할인은 못참지…발란, 5일간 250억 판매',
 "[단독] 생로랑도 '가격 인상' 대열 합류…루루 퍼퍼백 325만원→375만원",
 '[뉴리테일 시대 화두 중고거래 시장] PartⅠ 트렌드 주도하는 중고거래 플랫폼...',
 '[인사이드 차이나] ‘럭셔리 끝판왕’ 백화점도 문 닫았다…中 봉쇄 충격 강타',
 '[월요기획] 8.6조 마켓 명품… 영업익 평균 180% ↑',
 '카카오, 5월 가정의달 맞아 커머스 기획전',
 '카카오, 5월 가정의 달 맞아 푸짐한 기획전 마련',
 '[sportism] 봄, 아노락을 꺼낼 시간',
 '카카오, 가정의달 맞이 커머스 기획전 진행',
 "카카오, 5월 가정의 달 '커머스 기획전' 진행",
 '카카오, 가정의 달 기념 대규모 쇼핑 기획전',
 "카카오쇼핑라이브, 15일까지 명품 '뷰티 홀릭 위크' 진행",
 '카카오, 5월 가정의 달 맞아 커머스 기획전 진행',
 '플라워 원피스 스타일리시하게 입는 법 ①',
 '‘엔데믹 시대’, 돌아온 이태원의 불금',
 '셋째 주는 4일 근무, 레고랜드도 통째로 빌렸다…&quot;아빠 회사 최고&quot;',
 "루이비통, 고가의 가방 대신 8만원 짜리 '티세트' 파는 이유는?",
 "&quot;하이닉스만큼 안 바랍니다&quot;…1년 만에 반전된 삼성·SK '인재 쟁탈전'",
 "&quot;샤넬·구찌·<b>에르메스</b>?&quot;…명품에 꽂힌 '네카오' [IT돋보기]",
 '베블렌 효과',
 '고급화는 어디로…광희의 ‘네고’ 대상이 된 명품? [명품톡+]',
 '[추천템] 로맨틱한 서머 무드를 완성하는 과즙 립 컬렉션',
 '[이슈 크래커] 패션업계가 세일 끝나자 또 할인 나선 까닭은?',
 '아뜰리에 <b>에르메스</b>에서 열리는 로르 프루보의 전시를 멋지게 즐기는 방법',
 '[안재형 기자의 트렌드가 된 브랜드] 구찌 | 무명의 디렉터가 재건한 100년 명...',
 '중국 MZ세대, 명품 소비에 지갑 닫고 있다',
 "[Who's who] 블랙핑크 지수 마니아, 한국 방문한 피에트로 베카리 디올 회장",
 '봄을 담은 5월 향수 스페셜',
 '[지금 현장에서는…] 열리는 족족 예약 마감, 패션 명품사 F&amp;B도 접수',
 "'5조' 해외송금하는 이 기업들 탓?…환율 1300원 돌파 '초읽기' [김익환의 컴...",
 "'샤넬 2.55' 코시국에 6배 껑충…유럽에서 본 명품백 투자 열풍",
 "코로나 속 '고액 소비' 늘었다...명품업계 최고매출에도 가격은 '올린다'",
 "한국서 3조 쓸어모으더니…샤넬 등 명품업계 또 '가격인상설'",
 '[단독] 디올 이화여대 패션쇼, 백화점 CEO 한자리에',
 "&quot;아이돌에 '위협 운전' 피해 당했다&quot; 폭로한 여자 유튜버가 찬열 아니냐는 의...",
 '예술가와 디지털 투기꾼 사이: <b>에르메스</b> 버킨백 NFT 출시자, 상표권 침해로 피...',
 '&quot;엑소 찬열 피해 유감&quot;…위협운전·욕설 저격 유튜버, 뒤늦은 사과 [종합]',
 '사회가 죽음에 이르는 병, 서열문화',
 "[비즈브리핑] 루이 비통, 구찌 등 명품 브랜드들이 왜 '식당'을 열지?",
 '‘간판만 보고 다니는 회사 됐다’ 카카오에 연봉 추월당한 삼성맨들',
 '‘구찌’ 1분기 매출 14.4% 신장...‘기대 이하’',
 '미식의 습격...기업들의 이유있는 외도',
 '지난해 6번 올린 ‘프라다’ 또 올렸다…문신템 ‘호보백’ 149만원',
 '엑소 찬열, 위협운전+손가락 욕 아이돌? SM &quot;허위사실 강경 대응&quot;',
 "오토바이 탄 유튜버에 '손가락 욕' 날리며 위협 운전한 유명 남자 아이돌 (영...",
 '[이슈크래커] 이젠 ‘푸드’도 패션이다...구찌가 레스토랑을 오픈한 이유',
 "손안의 명품관 거듭난 '카카오톡 선물하기'",
 '디올·이화여대 장학금 기부 등 파트너쉽 ... 디올 패션쇼에 이대생\xa01000여명...',
 "[글로벌포스트] 비트코인, 3.8만달러로 '털썩'...급락 경고도 잇따라",
 "[알뜰 재테크] 예비 신혼부부를 위한 '혼수 준비' 추천 신용카드",
 "이대생들 디올 패션쇼 '광클'…순식간에 1000여명 몰렸다",
 '봉쇄 와중에도 재력 뽐내기?..현관문에 명품쇼핑백 내건 상하이 시민',
 '“화려한 청담동 떠나 반 평짜리 부엌서 행복 찾았죠”',
 '5월부터 8월까지 꼭 가야하는 전시들',
 '中 ‘MZ세대 명품 수요 크게 줄어든다’',
 "[패션 in 캐릭터] '킬힐' 한수연 &quot;상위 1% 패션, 집에서도 완벽하게&quot;",
 "상하이 주민들, 집 현관문에 '명품 쇼핑백' 내걸었다…이유는?",
 "[스타톡] '킬힐' 한수연 &quot;신애 연기하며 자신감 생겼죠&quot;",
 "&quot;큰 거 온다&quot;...롯데百 ,'초프리미엄'으로 완전무장",
 "한컵에 8.3만원…'빙수계 <b>에르메스</b>'도 완판행진?",
 '루이비통·샤넬, 작년 국내서 1조원 넘게 팔았다',
 '상하이 부자들의 돈자랑? 집 현관에 걸린 명품 쇼핑백의 정체',
 "'킬힐' 한수연 &quot;사이코패스 사모? 뿌듯한 별명이죠&quot;",
 "&quot;해외여행 막히자 명품 구매&quot; 백화점 '고액 소비' 증가",
 '해외여행 막히자… 백화점 가서 100만 원씩 팍팍 질렀다',
 "코로나에 해외여행 대신 명품 구매…백화점 '고액소비' 늘었다",
 "코로나 격리 키트 받기 위해 현관문마다 '명품 쇼핑백' 걸어놓는 상하이 시민...",
 "'해외여행 대신 쇼핑'...코로나19에 명품소비 증가",
 '크림에 묻습니다…3년 전 제품도 안뜯으면 신상인가요?',
 '&quot;해외여행 막히자 명품 등 구매&quot; 매출 급증',
 "코로나에 해외여행 대신 명품…백화점 '고액 소비' 늘었다",
 "[관점뉴스] 톰브라운부터 포켓몬까지...전자기기 시장에 불어온 '에디션' 열풍",
 "[종합] '우리사이' 김재경, god CD 구입 위해 강아지 목걸이 만들어 팔고 수입...",
 '일상을 빼앗긴 우크라이나를 향한 지지와 평화의 메세지',
 "대신證 IT기업 부럽지 않은 복지에 직원들 '활짝'",
 '포켓몬·BTS 품은 한정판 스마트폰, 실적엔 별 도움 안된다는데 왜?',
 '리본즈, 우수 인재 영입과 대규모 투자 통해 지속성장 박차',
 '[Business Inside] 역대 최대 실적 ‘에·루·샤’… 사회공헌은 쥐꼬리',
 '야옹이 작가, 샤넬 옷에 <b>에르메스</b>백까지..능력 있는 럭셔리 싱글맘',
 '생머리로 파격 변신한 오은영 “미스코리아 머리 왜 하냐고요?”',
 "샤넬, 구찌, 불가리...상하이 현관문마다 걸리는 '명품 쇼핑백' 논란 [특파원...",
 '박은지, 수천만 원 <b>에르메스</b>백이 데일리룩..&quot;일본 가고 싶다&quot;',
 '싱글 몰트 위스키의 향을 끌어올리는 페어링 6',
 "'보복소비'에 '베블렌 효과'까지…루이뷔통·샤넬·<b>에르메스</b> 역대 최대 실적",
 "드라마「파친코」'제주의 아픔 담아냈다'..⑥일제에 맞서 지켜 낸 '민족혼·정...",
 '“고객 정보는 비밀입니다” 럭셔리 브랜드는 구설수를 좋아할까 [명품톡+]',
 '‘워치스 앤 원더스 2022’ 트렌드 리포트.',
 '사랑하는 사람에게 선물하고 싶은 그루밍 아이템 33',
 '‘에.루.샤’ 인테리어 지원해 모신다는데, 베품 없고 수익만 쏙~',
 "'코로나 2년' 해외 명품만 날았다…패션, 올해 분위기는 다를까",
 '[Review] 동시대에 살고 있다는 건 - 마이클 크레이그 마틴展 [전시]',
 '머스트잇 매거진 Ep88, 무채색 VS 유채색',
 "'박재범 소주'에 '백걸리'까지…유명인 술 '전성시대'",
 '명품 지메틱(SieMatic)으로 완성한 ‘리미티드 에디션’ 럭셔리 시그니처 공간...',
 '[너와나의 소녀시대]‘파친코’ 그리고 1989년 버블 경제 속 일본',
 '요즘 홍대는 오타쿠 성지?…애니덕후, 홍대를 습격하다 [라인업]',
 '배달의민족의 ‘보틀넥’: 독점 기업인데요, 독점을 못 해요',
 '빈티지 컬러 네일 팔레트',
 "공사현장서 인부들 '명품지갑'만 골라 턴 40대에 실형 선고",
 '루이비통 등 명품 5곳, 한국서 실속 다 챙겼다',
 '최원철의 부동산 경제 뉴스',
 '<b>에르메스</b>의 여름 팔레트',
 '팬데믹 장기화 ‘보복소비’ 확산…과시형 소비, 명품업체들 好好',
 '[프롭테크 인사만사] ① 사람과 부동산을 잇는 기술…&quot;개발자를 모셔라&quot;',
 "[뉴스'까'페] IT발 연봉 인플레의 덫…‘머니게임’ 혹은 ‘치킨게임’",
 "명품 가격 계속 올리더니…지난해 '에루샤' 한국서 호실적",
 "비쌀수록 더 잘팔리다니…'에루샤' 명품업체 '돈방석'",
 "[30초뉴스] 비쌀수록 잘 팔린다?…철마다 가격 올린 명품업체들 '떼돈'",

In [34]:

data_title_tfidf = tfidf.transform(data_df['title'])

data_title_predict = SA_lr_best.predict(data_title_tfidf)

data_df['title_label'] = data_title_predict

In [35]:

data_description_tfidf = tfidf.transform(data_df['description'])

data_description_predict = SA_lr_best.predict(data_description_tfidf)

data_df['description_label'] = data_description_predict

In [36]:
data_df.head()

,title,description,title_label,description_label
0,&quot;결혼식 교복이냐&quot; 굴욕 겪은 샤넬…또 가격 인상설 솔솔,<b>에르메스</b>와 롤렉스는 매년 한 차례 씩 가격을 인상해왔다. 일각에서는 리...,0,1
1,너도 나도 팔목에 스마트워치…결국 ‘이 브랜드’ 관심 끌었다 [명품톡+],"이전에도 삼성과 톰브라운, 애플과 <b>에르메스</b>의 스마트워치 협업 소식은 있...",1,1
2,구찌·디올에 이어 세계 최초 루이비통 레스토랑까지... 왜 '코리아'일까,"루이비통 제공 <b>에르메스</b>, 구찌, 디올 등 콧대 높은 명품 브랜드들이 ...",0,1
3,"[유통 이슈] 헨켈홈케어코리아 브레프-패스트파이브, ‘상쾌한 화장실 조성 캠...","또, <b>에르메스</b>, 구찌, 랑콤, 디올, 다이슨 등 명품 브랜드 방송의 메...",0,1
4,"'10분 진료비가 9만원' 오은영 박사가 타고 다니는 차, 차원이 다른 수준이다","“가격에 입틀막” 오은영, <b>에르메스</b> VVIP 논란 이어 '초고가 명품 ...",1,0

In [37]:
data_df.to_csv(file_name+'.csv', encoding = 'utf-8')

In [38]:
data_df.head()

,title,description,title_label,description_label
0,&quot;결혼식 교복이냐&quot; 굴욕 겪은 샤넬…또 가격 인상설 솔솔,<b>에르메스</b>와 롤렉스는 매년 한 차례 씩 가격을 인상해왔다. 일각에서는 리...,0,1
1,너도 나도 팔목에 스마트워치…결국 ‘이 브랜드’ 관심 끌었다 [명품톡+],"이전에도 삼성과 톰브라운, 애플과 <b>에르메스</b>의 스마트워치 협업 소식은 있...",1,1
2,구찌·디올에 이어 세계 최초 루이비통 레스토랑까지... 왜 '코리아'일까,"루이비통 제공 <b>에르메스</b>, 구찌, 디올 등 콧대 높은 명품 브랜드들이 ...",0,1
3,"[유통 이슈] 헨켈홈케어코리아 브레프-패스트파이브, ‘상쾌한 화장실 조성 캠...","또, <b>에르메스</b>, 구찌, 랑콤, 디올, 다이슨 등 명품 브랜드 방송의 메...",0,1
4,"'10분 진료비가 9만원' 오은영 박사가 타고 다니는 차, 차원이 다른 수준이다","“가격에 입틀막” 오은영, <b>에르메스</b> VVIP 논란 이어 '초고가 명품 ...",1,0

In [39]:
data_df['title_label'].value_counts()

1    513
0    487
Name: title_label, dtype: int64

In [40]:
data_df['description_label'].value_counts()

1    672
0    328
Name: description_label, dtype: int64

In [41]:
#네이버 루이비통

In [42]:
import json

file_name = '루이비통_naver_news'
with open(file_name + '.json', encoding = 'utf8') as j_f:
    data = json.load(j_f)

In [43]:
data_title = []
data_description = []
for item in data:
    data_title.append(item['title'])
    data_description.append(item['description'])

data_df = pd.DataFrame({'title':data_title, 'description':data_description})

In [44]:

data_title_tfidf = tfidf.transform(data_df['title'])

data_title_predict = SA_lr_best.predict(data_title_tfidf)

data_df['title_label'] = data_title_predict

In [45]:

data_description_tfidf = tfidf.transform(data_df['description'])

data_description_predict = SA_lr_best.predict(data_description_tfidf)

data_df['description_label'] = data_description_predict

In [46]:
data_df.to_csv(file_name+'.csv', encoding = 'utf-8')

In [47]:
data_df['title_label'].value_counts()

1    505
0    495
Name: title_label, dtype: int64

In [48]:
data_df['description_label'].value_counts()

1    652
0    348
Name: description_label, dtype: int64

In [49]:
#네이버 샤넬

In [50]:
import json

file_name = '샤넬_naver_news'
with open(file_name + '.json', encoding = 'utf8') as j_f:
    data = json.load(j_f)

In [51]:
data_title = []
data_description = []
for item in data:
    data_title.append(item['title'])
    data_description.append(item['description'])

data_df = pd.DataFrame({'title':data_title, 'description':data_description})

In [52]:

data_title_tfidf = tfidf.transform(data_df['title'])

data_title_predict = SA_lr_best.predict(data_title_tfidf)

data_df['title_label'] = data_title_predict

In [53]:
data_description_tfidf = tfidf.transform(data_df['description'])

data_description_predict = SA_lr_best.predict(data_description_tfidf)

data_df['description_label'] = data_description_predict

In [54]:
data_df.to_csv(file_name+'.csv', encoding = 'utf-8')

In [55]:
data_df['title_label'].value_counts()

1    501
0    499
Name: title_label, dtype: int64

In [56]:
data_df['description_label'].value_counts()

1    569
0    431
Name: description_label, dtype: int64

In [57]:
#네이버 디올

In [58]:
import json

file_name = '디올_naver_news'
with open(file_name + '.json', encoding = 'utf8') as j_f:
    data = json.load(j_f)

In [59]:
data_title = []
data_description = []
for item in data:
    data_title.append(item['title'])
    data_description.append(item['description'])

data_df = pd.DataFrame({'title':data_title, 'description':data_description})

In [60]:

data_title_tfidf = tfidf.transform(data_df['title'])

data_title_predict = SA_lr_best.predict(data_title_tfidf)

data_df['title_label'] = data_title_predict

In [61]:
data_description_tfidf = tfidf.transform(data_df['description'])

data_description_predict = SA_lr_best.predict(data_description_tfidf)

data_df['description_label'] = data_description_predict

In [62]:
data_df.to_csv(file_name+'.csv', encoding = 'utf-8')

In [63]:
data_df['title_label'].value_counts()

1    540
0    460
Name: title_label, dtype: int64

In [64]:
data_df['description_label'].value_counts()

1    723
0    277
Name: description_label, dtype: int64